HEIGVD-Course-DAI/DAI-2022-Chill-Classe-B

src/main/java/ch/heigvd/dai/chill/domain/doriannheig/Swaf.java, src/test/java/ch/heigvd/dai/chill/domain/doriannheig/SwafTest.java
=> Add Swaf beer

src/main/java/ch/heigvd/dai/chill/domain/cgerro/Chouffe.java, src/test/java/ch/heigvd/dai/chill/domain/cgerro/ChouffeTest.java
=> Add chouffe beer with test

src/main/java/ch/heigvd/dai/chill/domain/mromano/Delirium.java, src/test/java/ch/heigvd/dai/chill/domain/mromano/DeliriumTest.java
=> Adding Delirium beer and tests

src/main/java/ch/heigvd/dai/chill/domain/Florianconti/Follette.java, src/test/java/ch/heigvd/dai/chill/domain/Florianconti/FolletteTest.java
=> Ajout de la follette

src/main/java/ch/heigvd/dai/chill/domain/kumochan/Beerhaviour.java, src/test/java/h/heigvd/dai/chill/domain/kumochan/BeerhaviourTest.java
=> Merge request for beerable code

src/main/java/ch/heigvd/dai/chill/domain/miguelJalube/PeerBong.java, src/test/java/ch/heigvd/dai/chill/domain/miguelJalube/PeerBongTest.java
The PeerBong beer has been created
=> Finished creating the BeerPong beer

src/main/java/ch/heigvd/dai/chill/domain/vino89/Peroni.java, src/test/java/ch/heigvd/dai/chill/domain/vino89/PeroniTest.java
=> Peroni Beer and PeroniTEst added

src/main/java/ch/heigvd/dai/chill/domain/alexisheig/Superbock.java, src/test/java/ch/heigvd/dai/chill/domain/alexisheig/SuperbockTest.java
=> Added Superbock

src/main/java/ch/heigvd/dai/chill/domain/Leandro4002/BlueMoon.java, src/test/java/ch/heigvd/dai/chill/domain/Leandro4002/BlueMoonTest.java
=> Added Blue Moon with tests

src/main/java/ch/heigvd/dai/chill/domain/moi1023/Heineken.java, src/test/java/ch/heigvd/dai/chill/domain/moi1023/HeinekenTest.java
=> Ajout Heineken et test Heineken

src/main/java/ch/heigvd/dai/chill/domain/hugoducom/Placebo.java, src/test/java/ch/heigvd/dai/chill/domain/hugoducom/PlaceboTest.java
=> Added Placebo beer

src/main/java/ch/heigvd/dai/chill/domain/Rouuuben/RouuubenBeer.java, src/test/java/ch/heigvd/dai/chill/domain/Rouuuben/RouuubenTest.java
Best beer ! Buy my beer pls, for only 555.55
=> Finish Rouuuuuuuuuuuuuuuuuuben Beer #29

src/main/java/ch/heigvd/dai/chill/domain/yvancochet/CaptainMousse.java, src/test/java/ch/heigvd/dai/chill/domain/yvancochet/CaptainMousseTest.java
=> Add captaine mousse beer, #52

src/main/java/ch/heigvd/dai/chill/domain/JorisDecoppetHeigVd/SuzeAOC.java, src/test/java/ch/heigvd/dai/chill/domain/JorisDecoppetHeigVd/SuzeAOCTest.java
=> add a new beer (SuzeAOC)

src/main/java/ch/heigvd/dai/chill/domain/xplyce/Boxer.java, src/test/java/ch/heigvd/dai/chill/domain/xplyce/BoxerTest.java
=> ajout biere Boxer

src/main/java/ch/heigvd/dai/chill/domain/kjorand/VintageSourBeer.java, src/test/java/ch/heigvd/dai/chill/domain/kjorand/VintageSourBeerTest.java
=> Added Vintage Sour Beer

src/main/java/ch/heigvd/dai/chill/domain/kevinferati/PrixGarantie.java, src/test/java/ch/heigvd/dai/chill/domain/kevinferati/PrixGarantieTest.java
=> Added the PG beer

src/main/java/ch/heigvd/dai/chill/domain/Greywind299792458/Delorean.java, src/test/java/ch/heigvd/dai/chill/domain/Greywind299792458/DeloreanTest.java
Close [#38](https://github.com/HEIGVD-Course-DAI/DAI-2022-Chill-Classe-B/issues/38)
=> added new Delorean Beer + test

src/main/java/ch/heigvd/dai/chill/domain/celestinPiccin/Lulz.java, src/test/java/ch/heigvd/dai/chill/domain/celestinPiccin/LulzTest.java
=> added lulz beer with test

fileToTestCLI.txt
From issue: #57 
Done through package: kc5_bp with unary test
=> Requesting adding Kraken' shot

src/main/java/ch/heigvd/dai/chill/domain/gumimax/Pietra.java, src/test/java/ch/heigvd/dai/chill/domain/gumimax/PietraTest.java
=> Adding Pietra beer
